export type QuizQuestion={question:string;options:string[];correct:number;explanation:string};
export type Chapter={slug:string;part:string;partTitle:string;title:string;intro:string;essential:string;detail:string;takeaway:string;practice:string;objectives:string[];whyItMatters:string;commonMistake:string;readingTime:number;quiz:QuizQuestion[]};
type Seed=[string,string,string,string];
const slugify=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const guides:Record<string,{importance:string;mistake:string;lens:string}>={
"parte-1":{importance:"Compreender a lógica do vinho dá autonomia para escolher e conversar sobre rótulos.",mistake:"Transformar uma pista em regra absoluta.",lens:"origem, elaboração e estilo"},
"parte-2":{importance:"Treinar os sentidos cria referências que nenhuma lista de notas consegue substituir.",mistake:"Procurar o aroma certo e desconsiderar a própria percepção.",lens:"sensação, intensidade e equilíbrio"},
"parte-3":{importance:"Conhecer a uva ajuda a antecipar possibilidades de aroma e estrutura.",mistake:"Imaginar que a mesma uva terá sempre o mesmo sabor.",lens:"clima, origem e modo de produção"},
"parte-4":{importance:"Ler a origem permite entender por que lugar e tradição influenciam o estilo.",mistake:"Reduzir um país inteiro a um único tipo de vinho.",lens:"clima, relevo, cultura e denominação"},
"parte-5":{importance:"Harmonização bem compreendida melhora a experiência da comida e do vinho.",mistake:"Tratar combinações como proibições ou fórmulas imutáveis.",lens:"intensidade, gordura, sal, acidez e textura"},
"parte-6":{importance:"Boas pistas de compra reduzem frustração e ajudam a descobrir mais dentro do orçamento.",mistake:"Confundir preço, pontuação ou embalagem com garantia de prazer.",lens:"ocasião, procedência, estilo e valor"},
"parte-7":{importance:"Cuidados simples preservam o vinho até o momento de abrir a garrafa.",mistake:"Buscar equipamentos sofisticados antes de garantir estabilidade e proteção.",lens:"temperatura, luz, tempo e vedação"},
"parte-8":{importance:"Técnicas e conceitos avançados explicam nuances que aparecem na textura, nos aromas e na evolução.",mistake:"Usar jargão como atalho para qualidade sem observar o resultado na taça.",lens:"intenção, método, equilíbrio e resultado"}
};
const rotate=(options:string[],correct:string,shift:number)=>{const moved=options.map((_,i)=>options[(i+shift)%options.length]);return{options:moved,correct:moved.indexOf(correct)}};
const build=(part:string,partTitle:string,seeds:Seed[]):Chapter[]=>seeds.map(([title,intro,takeaway,practice],index)=>{
  const guide=guides[part];
  const q1Correct=takeaway;const q1=rotate([q1Correct,"O preço do vinho é a única pista realmente confiável.","Existe uma resposta universal, independente do contexto.","A experiência pessoal deve ser ignorada."],q1Correct,(title.length+index)%4);
  const q2Correct=practice;const q2=rotate([q2Correct,"Memorizar rankings sem provar nenhum exemplo.","Escolher apenas pela aparência do rótulo.","Evitar comparações para não influenciar a opinião."],q2Correct,(title.length+index+1)%4);
  const q3Correct="Verdadeiro";const q3=rotate([q3Correct,"Falso"],q3Correct,(title.length+index)%2);
  return{slug:slugify(title),part,partTitle,title,intro,essential:intro,
    detail:`${takeaway} Para entender essa ideia de verdade, observe ${guide.lens}. Dois vinhos da mesma categoria podem mostrar resultados distintos porque lugar, matéria-prima, tempo e decisões humanas trabalham em conjunto. A comparação consciente transforma a teoria em memória.` ,takeaway,practice,
    objectives:[`Explicar “${title}” sem depender de jargões.`,`Reconhecer como ${guide.lens} aparecem na experiência.`,`Aplicar o conceito por meio de uma comparação prática.`],
    whyItMatters:`${guide.importance} ${takeaway} Esse olhar permite fazer perguntas melhores, interpretar diferenças e construir preferência com mais segurança.`,
    commonMistake:`${guide.mistake} Em “${title}”, contexto e comparação valem mais que conclusões apressadas.`,
    readingTime:6+(index%4),
    quiz:[
      {question:`Qual afirmação resume melhor o capítulo “${title}”?`,options:q1.options,correct:q1.correct,explanation:`A ideia central é: ${takeaway}`},
      {question:`Qual experiência prática ajuda a consolidar “${title}”?`,options:q2.options,correct:q2.correct,explanation:`A prática sugerida é: ${practice}`},
      {question:`Verdadeiro ou falso: ${takeaway}`,options:q3.options,correct:q3.correct,explanation:`Verdadeiro. ${intro}`}
    ]};
});

export const chapterParts=[
{id:"parte-1",label:"Parte I",title:"Entendendo o vinho"},{id:"parte-2",label:"Parte II",title:"Aprendendo a degustar"},{id:"parte-3",label:"Parte III",title:"Uvas"},{id:"parte-4",label:"Parte IV",title:"Regiões"},{id:"parte-5",label:"Parte V",title:"Harmonização"},{id:"parte-6",label:"Parte VI",title:"Comprar vinho"},{id:"parte-7",label:"Parte VII",title:"Adega"},{id:"parte-8",label:"Parte VIII",title:"Nível avançado"}
];

export const chapters:Chapter[]=[
...build("parte-1","Entendendo o vinho",[
["Afinal, o que é vinho?","Vinho é a bebida criada quando leveduras transformam os açúcares do suco da uva em álcool, gás carbônico e calor.","Uma definição simples abre espaço para enormes diferenças de uva, lugar e produção.","Compare três estilos e descreva apenas as diferenças que você percebe."],
["Tinto, branco, rosé, espumante e fortificado","Cor, borbulhas, doçura e teor alcoólico nascem de escolhas de matéria-prima e elaboração — não de uma escala de qualidade.","Cada estilo resolve a relação entre cascas, fermentação, gás e álcool de uma maneira.","Sirva um branco, um tinto e um espumante lado a lado e compare peso e frescor."],
["Como o vinho é produzido","Colheita, esmagamento, fermentação, amadurecimento e engarrafamento formam a espinha dorsal da vinificação.","Pequenas decisões em cada etapa mudam aromas, textura e capacidade de guarda.","Ao provar, tente imaginar se o vinho valoriza fruta fresca, extração ou madeira."],
["O que é safra","Safra é o ano da colheita das uvas e ajuda a contextualizar clima, evolução e estilo.","O ano importa mais em algumas regiões e vinhos do que em outros; não é uma nota automática de qualidade.","Escolha o mesmo rótulo em duas safras e registre semelhanças e diferenças."],
["Como ler um rótulo","Produtor, origem, safra, uva, denominação e teor alcoólico oferecem pistas — mesmo quando a frente do rótulo parece enigmática.","Rótulos do Velho Mundo tendem a destacar lugar; muitos do Novo Mundo destacam a uva.","Fotografe um rótulo e localize produtor, país, região, safra e álcool."],
["Velho Mundo x Novo Mundo","Velho e Novo Mundo são atalhos culturais e geográficos, não caixas rígidas de sabor.","Europa costuma valorizar denominações e tradição; outros países frequentemente comunicam uva e fruta com mais clareza.","Compare um Cabernet francês e um chileno na mesma faixa de preço."],
["O que faz um vinho custar R$ 50, R$ 200 ou R$ 1.000","Terra, rendimento, trabalho manual, tempo, barricas, reputação, impostos e raridade participam do preço.","Preço e prazer não crescem na mesma proporção; valor depende também do contexto e de quem bebe.","Faça uma degustação às cegas com três faixas de preço e só depois revele os rótulos."]]),
...build("parte-2","Aprendendo a degustar",[
["Taças e temperatura","A taça conduz aromas e a temperatura altera a percepção de álcool, frescor e textura.","Uma boa taça universal e a temperatura correta ajudam mais do que uma coleção de formatos.","Prove o mesmo vinho mais frio e depois alguns graus mais quente."],
["Análise visual","Cor, brilho, limpidez e intensidade oferecem pistas, mas raramente entregam uma conclusão sozinhos.","Observar prepara os sentidos e ajuda a acompanhar a evolução do vinho.","Incline a taça sobre fundo branco e descreva centro e borda sem julgar qualidade."],
["Aromas","Aromas podem lembrar frutas, flores, ervas, especiarias, madeira e evolução, embora o vinho não contenha necessariamente esses ingredientes.","Nomear aromas é construir associações de memória, não acertar um gabarito secreto.","Cheire três frutas ou especiarias antes da próxima degustação."],
["Como provar","Olhar, cheirar, tomar um pequeno gole, espalhar o vinho e observar a sequência organiza a experiência.","Degustar é prestar atenção; cuspir é opcional fora de contextos profissionais.","Faça dois goles: um espontâneo e outro concentrado em textura e final."],
["Acidez","Acidez provoca frescor e salivação, sustenta o vinho e pode equilibrar doçura e gordura.","Ela é sensação tátil e estrutural, não simplesmente gosto de limão.","Compare água, água com poucas gotas de limão e um vinho branco seco."],
["Taninos","Taninos vêm sobretudo de cascas, sementes, engaços e madeira e produzem estrutura e adstringência.","Eles podem ser finos, macios, firmes ou secantes — intensidade e qualidade são coisas diferentes.","Compare chá preto forte, banana verde e um tinto estruturado."],
["Álcool","Álcool contribui para calor, volume, textura e transporte de aromas.","Equilíbrio importa mais que o número isolado no rótulo.","Compare rótulos com teores diferentes e observe calor no final do gole."],
["Corpo","Corpo é a sensação de peso e volume do vinho na boca.","Álcool, açúcar, concentração e textura ajudam a formar essa percepção.","Use leite desnatado, integral e creme como analogia tátil."],
["Doçura","Doçura vem do açúcar residual e deve ser distinguida da fruta madura percebida nos aromas.","Um vinho pode cheirar doce e ainda ser seco.","Compare um vinho seco, um meio-seco e um doce observando o final do gole."],
["Persistência","Persistência é o tempo e a qualidade das sensações depois de engolir ou cuspir.","Final longo só é positivo quando o que permanece é agradável e integrado.","Conte mentalmente os segundos e anote quais sensações ficam."],
["Equilíbrio","Equilíbrio acontece quando acidez, álcool, taninos, fruta e doçura convivem sem um elemento dominar de forma incômoda.","Equilíbrio muda conforme estilo, temperatura, comida e preferência.","Dê uma nota separada a cada elemento antes de avaliar o conjunto."],
["Como fazer uma ficha de degustação","Uma ficha transforma impressão passageira em memória comparável.","Registrar pouco e com constância é melhor que preencher tecnicamente uma única vez.","Registre aparência, aromas, estrutura, nota e se compraria novamente."]]),
...build("parte-3","Uvas",[
["Cabernet Sauvignon","Cabernet Sauvignon costuma unir corpo, acidez, taninos e aromas de cassis, frutas escuras, ervas e cedro.","Clima e amadurecimento mudam o equilíbrio entre fruta, frescor e notas vegetais.","Compare um exemplo chileno com um de Bordeaux ou da Serra Gaúcha."],
["Merlot","Merlot tende a oferecer textura mais macia e fruta de ameixa e cereja, sem perder capacidade de profundidade.","Ela pode ser acessível quando jovem ou séria e longeva em grandes terroirs.","Compare Merlot e Cabernet da mesma região."],
["Pinot Noir","Pinot Noir costuma ser clara, perfumada, fresca e delicada em taninos.","Delicadeza não significa simplicidade; origem e evolução aparecem com grande nitidez.","Sirva levemente fresca e observe frutas vermelhas, flores e notas terrosas."],
["Syrah e Shiraz","Syrah pode mostrar amora, violeta, pimenta e defumado; Shiraz frequentemente indica expressão mais madura e generosa.","Os nomes também carregam escolhas regionais e de estilo, não duas uvas diferentes.","Compare Rhône, Austrália e Vale do São Francisco."],
["Malbec","Malbec combina cor profunda, fruta escura, violetas e taninos que variam do suculento ao firme.","Altitude em Mendoza ajuda a conservar frescor em ambientes ensolarados.","Compare um Malbec de altitude com outro de região mais quente."],
["Tempranillo","Tempranillo é a espinha dorsal de muitos tintos espanhóis, com cereja, ameixa, couro e especiarias.","Tempo de amadurecimento e madeira marcam estilos de Rioja e Ribera del Duero.","Compare Crianza e Reserva sem presumir que mais madeira é sempre melhor."],
["Sangiovese","Sangiovese equilibra cereja, ervas, terra e acidez vibrante.","Sua acidez explica a afinidade com tomate, massas e cozinha toscana.","Prove com molho de tomate e depois sem comida."],
["Nebbiolo","Nebbiolo combina cor relativamente clara com taninos e acidez elevados, além de rosas, cereja, alcatrão e especiarias.","Aparência leve não determina estrutura leve.","Observe como o vinho muda após uma hora na taça."],
["Carménère","Carménère mistura fruta escura, especiarias e notas herbais, hoje fortemente ligada ao Chile.","Maturação adequada evita que o verde domine a fruta.","Compare Carménère e Cabernet chilenos."],
["Chardonnay","Chardonnay vai do cítrico e mineral ao cremoso e amanteigado, conforme clima e vinificação.","Carvalho e fermentação malolática são escolhas, não características obrigatórias da uva.","Compare um Chardonnay sem madeira com um amadurecido em barrica."],
["Sauvignon Blanc","Sauvignon Blanc costuma unir acidez alta a cítricos, ervas, maracujá e notas minerais.","Clima e origem mudam o eixo entre perfil vegetal e fruta tropical.","Compare Loire e Nova Zelândia."],
["Riesling","Riesling é aromática, muito ácida e capaz de estilos secos a intensamente doces.","Doçura e acidez podem coexistir em grande equilíbrio.","Confira o teor alcoólico e tente estimar se há açúcar residual."],
["Chenin Blanc","Chenin Blanc combina acidez firme, maçã, pera, flores, mel e enorme versatilidade.","A mesma uva produz espumantes, secos, doces e vinhos de guarda.","Compare um Chenin seco e um com doçura perceptível."],
["Moscato","Moscato é imediatamente aromática, lembrando uva fresca, flores, pêssego e cítricos.","Baixo álcool, doçura e borbulhas podem formar um conjunto leve e fresco.","Sirva bem fria com fruta ou sobremesa delicada."],
["Gewürztraminer","Gewürztraminer é exuberante, com lichia, rosas e especiarias, acidez moderada e textura ampla.","Intensidade aromática pede atenção ao equilíbrio e à comida.","Experimente com pratos aromáticos e levemente picantes."]]),
...build("parte-4","Regiões",[
["França","A França organiza grande parte de seus vinhos pela origem: Bordeaux, Borgonha, Champagne, Rhône, Loire e Alsácia.","Região e denominação frequentemente dizem mais que a uva no rótulo.","Escolha duas regiões e identifique uvas, clima e estilo dominante."],
["Itália","A diversidade italiana liga centenas de uvas a cozinhas e paisagens locais, de Piemonte e Toscana a Vêneto e Sicília.","Denominações ajudam, mas produtor e estilo continuam decisivos.","Compare Sangiovese da Toscana e Nebbiolo do Piemonte."],
["Portugal","Portugal oferece grande diversidade de uvas autóctones e estilos no Douro, Dão, Alentejo, Vinho Verde e Madeira.","Blends tradicionais podem ser mais importantes que o nome de uma única uva.","Procure no contrarrótulo as variedades de um corte português."],
["Espanha","Rioja, Ribera del Duero, Priorat, Rías Baixas e Jerez mostram a amplitude espanhola.","Tempo de amadurecimento e categorias tradicionais ajudam a entender muitos rótulos.","Compare um branco de Albariño e um tinto de Tempranillo."],
["Argentina","Mendoza lidera a imagem argentina, com Malbec de diferentes altitudes, mas Patagônia, Salta e outras áreas ampliam o mapa.","Altitude pode preservar acidez e mudar aroma, textura e maturação.","Compare duas indicações de altitude no rótulo."],
["Chile","Entre Andes e Pacífico, Chile reúne vales como Maipo, Colchagua, Casablanca e Itata.","Distância do mar e relevo ajudam a explicar climas muito diferentes.","Compare Sauvignon Blanc costeiro e Cabernet de vale interior."],
["Estados Unidos","Califórnia, Oregon e Washington formam polos distintos, com Napa, Sonoma e Willamette entre os nomes mais conhecidos.","Produtor e área específica são pistas importantes num sistema flexível.","Compare Pinot Noir de Oregon e Cabernet da Califórnia."],
["África do Sul","África do Sul une história e modernidade em Stellenbosch, Swartland e regiões costeiras.","Chenin Blanc e Pinotage oferecem portas de entrada marcantes.","Prove Chenin sul-africano e observe fruta, textura e acidez."],
["Austrália","Austrália vai muito além de Shiraz potente: Barossa, Margaret River, Yarra e Clare têm identidades diferentes.","Clima regional é mais informativo que a ideia genérica de país quente.","Compare Shiraz de Barossa e Riesling de Clare Valley."],
["Nova Zelândia","Nova Zelândia ganhou fama com Sauvignon Blanc de Marlborough e também se destaca em Pinot Noir e Chardonnay.","Ilhas, latitude e influência marítima sustentam frescor e aromas nítidos.","Compare Sauvignon neozelandês com um do Loire."],
["Brasil","Serra Gaúcha, Vale dos Vinhedos, Campanha Gaúcha e novas regiões mostram diversidade, com destaque internacional para espumantes.","Clima, altitude, colheita e técnica desafiam a ideia de um único estilo brasileiro.","Compare um espumante brasileiro, um Merlot do Vale dos Vinhedos e um vinho da Campanha."]]),
...build("parte-5","Harmonização",[
["Carnes","Corte, gordura, molho e preparo importam mais que a palavra carne.","Intensidade equivalente e taninos amaciados por proteína são bons pontos de partida.","Compare o mesmo tinto com carne magra e corte gorduroso."],
["Churrasco","Fumaça, gordura, sal e variedade de cortes pedem vinhos versáteis e com presença.","Malbec, Syrah, Tannat e Tempranillo tendem a funcionar, sem formar regra absoluta.","Teste um tinto frutado com dois cortes diferentes."],
["Massas","A massa é neutra; molho, recheio e queijo comandam a harmonização.","Tomate pede acidez, molhos cremosos pedem frescor e ragus aceitam mais corpo.","Escolha o vinho só depois de definir o molho."],
["Pizza","Tomate, queijo, gordura e coberturas tornam a pizza excelente campo de experimentação.","Tintos de boa acidez e corpo moderado costumam ser parceiros flexíveis.","Compare Sangiovese e Merlot com a mesma pizza."],
["Peixes","Textura, gordura, molho e técnica definem se o peixe pede branco, rosé, espumante ou até tinto leve.","Tintos muito tânicos podem criar choque com peixes delicados.","Experimente Pinot Noir levemente fresco com salmão."],
["Frutos do mar","Salinidade e delicadeza favorecem acidez, frescor e pouco tanino.","Alvarinho, Sauvignon Blanc e espumantes são pontos de partida, não limites.","Experimente um branco fresco com sururu e observe a salinidade."],
["Queijos","Intensidade, sal, gordura e maturação do queijo orientam a escolha.","Queijo forte nem sempre pede tinto forte; vinhos doces podem criar contrastes brilhantes.","Monte três queijos e prove cada um com o mesmo vinho."],
["Comida japonesa","Peixe cru, arroz avinagrado, shoyu, gengibre e wasabi criam desafios diferentes.","Riesling, espumante, Sauvignon Blanc e Pinot Noir leve tendem a ser versáteis.","Dose o shoyu e veja como ele muda o vinho."],
["Comida nordestina","Carne de sol, sururu, queijo coalho, coco, dendê e pimenta pedem olhar para intensidade e textura.","Acidez refresca, fruta acolhe especiarias e taninos devem respeitar sal e picância.","Compare Syrah com carne de sol e branco fresco com sururu."],
["Sobremesas","O vinho deve ser ao menos tão doce quanto a sobremesa para não parecer amargo ou magro.","Acidez impede que a combinação fique cansativa.","Compare sobremesa com vinho seco e depois com vinho doce."],
["Chocolate","Cacau, açúcar e gordura pedem potência, doçura e sabor persistente.","Porto, Banyuls e Moscatel funcionam de modos diferentes conforme o tipo de chocolate.","Compare chocolate ao leite e amargo com o mesmo vinho doce."]]),
...build("parte-6","Comprar vinho",[
["Comprar no supermercado","Supermercados oferecem conveniência, mas exigem atenção a armazenamento, giro e informação disponível.","Defina estilo, orçamento e ocasião antes de olhar promoções.","Escolha três rótulos e justifique qual pista do rótulo orientou cada opção."],
["Loja especializada","Uma boa loja traduz preferências em recomendações e guarda histórico do que funcionou.","Descrever ocasião e sensações desejadas ajuda mais que pedir simplesmente o melhor vinho.","Peça duas opções na mesma faixa e pergunte a diferença entre elas."],
["Escolher no restaurante","Carta, comida, serviço e preço formam uma decisão coletiva.","Faixas intermediárias, taças e ajuda do sommelier podem oferecer melhor descoberta.","Informe orçamento e prato antes de pedir recomendação."],
["Comprar em e-commerce","Variedade e comparação são vantagens; procedência, transporte e política de troca precisam ser verificados.","Preço muito baixo sem contexto merece cautela.","Compare preço final, reputação, armazenamento e prazo de três lojas."],
["Entender rótulos","Rótulo é um conjunto de pistas sobre origem, estilo e responsabilidade legal.","Contrarrótulo e ficha técnica frequentemente respondem ao que a frente omite.","Leia a frente e o verso antes de pesquisar o vinho."],
["Avaliar a safra","Safra contextualiza clima e idade, mas não substitui produtor, armazenamento e estilo.","Vinhos simples podem ser melhores jovens; grandes vinhos podem pedir tempo.","Pesquise se o rótulo foi pensado para juventude ou guarda."],
["Conhecer o produtor","Consistência, filosofia, vinhedos e técnica ajudam a prever estilo.","Produtor confiável pode ser pista mais útil que uma safra famosa.","Prove dois rótulos do mesmo produtor e procure a assinatura comum."],
["Denominação de origem","Denominações protegem nomes e estabelecem regras geográficas e produtivas.","Elas indicam pertencimento e padrão, não garantem gosto pessoal.","Identifique no rótulo a denominação e pesquise duas regras básicas."],
["Pontuações, preço e qualidade","Notas resumem a avaliação de alguém sob determinadas condições.","Use pontuação como referência, nunca como substituta do próprio gosto; preço inclui fatores além da qualidade sensorial.","Faça sua nota antes de consultar críticos e compare depois."]]),
...build("parte-7","Adega",[
["Armazenamento","Vinho prefere estabilidade, escuridão e ausência de vibração e calor excessivo.","Oscilações constantes podem ser mais prejudiciais que uma temperatura apenas um pouco acima do ideal.","Mapeie o lugar mais estável e escuro da casa."],
["Temperatura de guarda","Temperatura moderada e estável desacelera a evolução e protege aromas.","Adega de serviço e guarda podem ter objetivos diferentes.","Meça por uma semana a variação do local onde guarda garrafas."],
["Posição da garrafa","Garrafas com rolha natural costumam ficar deitadas para manter contato; outras vedações permitem mais flexibilidade.","O tipo de fechamento orienta a posição.","Separe sua adega por rolha natural, sintética e tampa de rosca."],
["Luz","Luz intensa e radiação ultravioleta aceleram reações e podem danificar sobretudo vinhos delicados.","Vidro escuro ajuda, mas não substitui armazenamento protegido.","Retire garrafas de exposição direta e caixas iluminadas."],
["Umidade","Umidade muito baixa pode ressecar rolhas; excesso favorece mofo e danos aos rótulos.","Estabilidade e ventilação importam mais que perseguir um número perfeito em casa.","Observe rolhas, rótulos e sinais de condensação."],
["Adega climatizada","Capacidade, zona de temperatura, ruído, ventilação e espaço real para garrafas definem a escolha.","O número anunciado de garrafas costuma considerar formatos padronizados.","Liste quantas garrafas pretende guardar e por quanto tempo."],
["Conservação após abertura","Oxigênio transforma o vinho; frio, vedação e menor contato com ar desaceleram o processo.","O tempo útil varia por estilo e condição inicial.","Prove a mesma garrafa em três dias e registre a evolução."],
["Decantação","Decantar pode separar sedimentos ou acelerar contato com oxigênio.","Vinhos jovens e antigos pedem objetivos e cuidados diferentes.","Compare duas taças, uma servida direto e outra após aeração."],
["Aerador","Aeradores aumentam rapidamente o contato com ar, mas não substituem tempo em todos os vinhos.","Eles podem ajudar tintos jovens e também apagar delicadeza.","Teste lado a lado antes de usar em toda a garrafa."],
["Taças e abridores","Ferramentas simples, limpas e confortáveis resolvem a maior parte das situações.","Uma taça universal fina e um saca-rolhas de dois estágios formam um ótimo começo.","Treine abertura segura e compare a mesma bebida em dois formatos de taça."]]),
...build("parte-8","Nível avançado",[
["Terroir","Terroir descreve a interação entre clima, solo, relevo, videira e ação humana ao longo do tempo.","Não é um sabor isolado, mas uma forma de interpretar origem e regularidade.","Compare a mesma uva em duas regiões e formule uma hipótese sobre o lugar."],
["Barricas","Barricas permitem evolução lenta, troca de oxigênio e, quando novas, transferência de compostos aromáticos e tânicos.","Tamanho, idade, origem e tempo mudam o efeito.","Compare vinho sem madeira e com madeira claramente perceptível."],
["Carvalho francês","Carvalho francês tende a oferecer textura e especiarias de modo mais sutil, embora tostagem e uso sejam decisivos.","Origem da madeira sozinha não define qualidade.","Busque notas de cedro, especiarias e estrutura sem confundi-las com fruta."],
["Carvalho americano","Carvalho americano frequentemente marca coco, baunilha e doçura aromática com maior evidência.","O efeito depende de barrica, tostagem, idade e tempo.","Compare Rioja tradicional e um vinho sem passagem por madeira."],
["Fermentação malolática","Bactérias transformam ácido málico mais cortante em ácido lático mais macio.","O processo reduz sensação de acidez e pode trazer notas amanteigadas, mas não cria necessariamente um vinho pesado.","Compare dois Chardonnays com fichas técnicas diferentes."],
["Sur lie","Sur lie significa manter o vinho em contato com borras finas após a fermentação.","O contato pode acrescentar textura, complexidade e proteção.","Procure sensação cremosa e notas de pão em branco ou espumante."],
["Bâtonnage","Bâtonnage é a agitação periódica das borras durante o amadurecimento.","Pode ampliar textura e aromas, mas excesso também pesa o conjunto.","Compare fichas técnicas e tente identificar cremosidade."],
["Vinho natural","Vinho natural é um movimento de mínima intervenção sem definição legal universal em muitos mercados.","Transparência do produtor importa mais que slogans; defeito e autenticidade não são sinônimos.","Prove às cegas um natural e um convencional da mesma uva."],
["Vinho biodinâmico","Biodinâmica trata o vinhedo como organismo integrado e segue práticas agrícolas e calendários próprios.","Certificação descreve manejo, não garante um perfil de sabor.","Pesquise a certificação e as práticas do produtor."],
["Vinho orgânico","Produção orgânica restringe insumos sintéticos no vinhedo conforme normas locais.","Uva orgânica e vinho orgânico podem seguir regras diferentes de elaboração e rotulagem.","Localize o selo e consulte o padrão que ele representa."],
["Maceração carbônica","Cachos inteiros em ambiente rico em gás carbônico iniciam fermentação dentro das bagas.","O método favorece fruta vibrante, taninos macios e aromas característicos.","Experimente um Beaujolais jovem levemente fresco."],
["Blends","Blend combina uvas, parcelas, safras ou lotes para buscar equilíbrio, consistência ou complexidade.","Corte não significa vinho inferior nem varietal significa pureza superior.","Tente identificar o papel de estrutura, aroma e frescor em um blend."],
["Potencial de guarda","Guarda depende de concentração, acidez, taninos, açúcar, álcool, equilíbrio, fechamento e armazenamento.","Capacidade de envelhecer não significa que o vinho ficará melhor para todos.","Escolha uma garrafa adequada, registre o estado atual e planeje quando reavaliar."]])
];
