export type Grape = { slug:string; name:string; color:"Tinta"|"Branca"; origin:string; summary:string; body:number; tannin:number; acidity:number; alcohol:number; aromas:string[]; regions:string[]; pairings:string[]; temperature:string; accent:string };
export const grapes:Grape[]=[
{slug:"cabernet-sauvignon",name:"Cabernet Sauvignon",color:"Tinta",origin:"Bordeaux, França",summary:"Estruturada, intensa e uma excelente escola para perceber taninos.",body:5,tannin:5,acidity:4,alcohol:4,aromas:["Cassis","Amora","Cedro","Pimenta"],regions:["Bordeaux","Napa Valley","Maipo","Coonawarra"],pairings:["Carne de sol","Churrasco","Queijos curados"],temperature:"16–18 °C",accent:"#702c3c"},
{slug:"merlot",name:"Merlot",color:"Tinta",origin:"Bordeaux, França",summary:"Macia, frutada e acolhedora — uma ótima porta de entrada para os tintos.",body:4,tannin:3,acidity:3,alcohol:4,aromas:["Ameixa","Cereja","Chocolate","Ervas"],regions:["Bordeaux","Toscana","Vale Central","Serra Gaúcha"],pairings:["Massas","Pizza","Escondidinho"],temperature:"15–17 °C",accent:"#95404d"},
{slug:"pinot-noir",name:"Pinot Noir",color:"Tinta",origin:"Borgonha, França",summary:"Delicada e perfumada, mostra que intensidade não depende apenas de peso.",body:2,tannin:2,acidity:4,alcohol:3,aromas:["Morango","Cereja","Rosas","Terra úmida"],regions:["Borgonha","Oregon","Patagônia","Central Otago"],pairings:["Salmão","Cogumelos","Comida japonesa"],temperature:"13–15 °C",accent:"#b9656d"}
];
export const glossary=[
{term:"Acidez",text:"A sensação de frescor e salivação. Pense na vivacidade de uma fruta cítrica."},{term:"Adstringência",text:"A sensação de boca seca provocada principalmente pelos taninos."},{term:"Corpo",text:"A percepção de peso e volume do vinho na boca: leve, médio ou encorpado."},{term:"Safra",text:"O ano em que as uvas foram colhidas — não necessariamente o ano de engarrafamento."},{term:"Tanino",text:"Composto presente sobretudo nas cascas, sementes e engaços; dá estrutura e adstringência."},{term:"Terroir",text:"A interação entre lugar, clima, solo, relevo e trabalho humano que influencia o vinho."},{term:"Varietal",text:"Vinho elaborado principalmente, ou integralmente, com uma variedade de uva."}
];
export const pairings:Record<string,{wines:string[];why:string}>={
"Carne de sol":{wines:["Syrah","Malbec","Tempranillo"],why:"A intensidade da carne tende a funcionar com vinhos de médio a alto corpo; fruta e taninos ajudam a equilibrar gordura e sabor."},Sururu:{wines:["Sauvignon Blanc","Alvarinho","Espumante Brut"],why:"Acidez e frescor acompanham a salinidade e a delicadeza do prato sem esconder seus sabores."},Pizza:{wines:["Sangiovese","Merlot","Barbera"],why:"Boa acidez conversa com o tomate, enquanto corpo moderado acompanha queijo e recheios."},"Comida japonesa":{wines:["Riesling","Pinot Noir","Espumante Brut"],why:"Perfis frescos e aromáticos costumam respeitar a delicadeza do peixe e lidar bem com shoyu e gengibre."},Chocolate:{wines:["Porto Ruby","Banyuls","Moscatel"],why:"A doçura do vinho deve acompanhar ou superar a da sobremesa; vale experimentar diferentes intensidades."}
};
